// DOGDLE Breed Dataset
// Fields: id, name, size, sizeOrder, shed, shedOrder, groom, groomOrder,
//         coat, active, activeOrder, lifespanLow, lifespanHigh,
//         origin, originRegion, dogCeoPath, petfinderName

export const BREEDS = [
  {
    id: "labrador-retriever",
    name: "Labrador Retriever",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Canada", originRegion: "North America",
    dogCeoPath: "retriever/labrador",
    petfinderName: "Labrador Retriever"
  },
  {
    id: "golden-retriever",
    name: "Golden Retriever",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "retriever/golden",
    petfinderName: "Golden Retriever"
  },
  {
    id: "german-shepherd",
    name: "German Shepherd",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 9, lifespanHigh: 13,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "germanshepherd",
    petfinderName: "German Shepherd Dog"
  },
  {
    id: "french-bulldog",
    name: "French Bulldog",
    size: "S", sizeOrder: 2,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "France", originRegion: "Europe",
    dogCeoPath: "bulldog/french",
    petfinderName: "French Bulldog"
  },
  {
    id: "bulldog",
    name: "Bulldog",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 8, lifespanHigh: 10,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "bulldog/english",
    petfinderName: "Bulldog"
  },
  {
    id: "poodle",
    name: "Poodle",
    size: "L", sizeOrder: 4,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Curly",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 18,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "poodle/standard",
    petfinderName: "Poodle"
  },
  {
    id: "beagle",
    name: "Beagle",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "beagle",
    petfinderName: "Beagle"
  },
  {
    id: "rottweiler",
    name: "Rottweiler",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 8, lifespanHigh: 10,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "rottweiler",
    petfinderName: "Rottweiler"
  },
  {
    id: "dachshund",
    name: "Dachshund",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 16,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "dachshund",
    petfinderName: "Dachshund"
  },
  {
    id: "pembroke-welsh-corgi",
    name: "Pembroke Welsh Corgi",
    size: "S", sizeOrder: 2,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "corgi/cardigan",
    petfinderName: "Welsh Corgi, Pembroke"
  },
  {
    id: "australian-shepherd",
    name: "Australian Shepherd",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "USA", originRegion: "North America",
    dogCeoPath: "australian/shepherd",
    petfinderName: "Australian Shepherd"
  },
  {
    id: "yorkshire-terrier",
    name: "Yorkshire Terrier",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 11, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "terrier/yorkshire",
    petfinderName: "Yorkshire Terrier"
  },
  {
    id: "boxer",
    name: "Boxer",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "boxer",
    petfinderName: "Boxer"
  },
  {
    id: "siberian-husky",
    name: "Siberian Husky",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "Russia", originRegion: "Europe",
    dogCeoPath: "husky",
    petfinderName: "Siberian Husky"
  },
  {
    id: "cavalier-king-charles-spaniel",
    name: "Cavalier King Charles Spaniel",
    size: "S", sizeOrder: 2,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 9, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "spaniel/cavalier",
    petfinderName: "Cavalier King Charles Spaniel"
  },
  {
    id: "doberman-pinscher",
    name: "Doberman Pinscher",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "doberman",
    petfinderName: "Doberman Pinscher"
  },
  {
    id: "great-dane",
    name: "Great Dane",
    size: "XL", sizeOrder: 5,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 7, lifespanHigh: 10,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "dane/great",
    petfinderName: "Great Dane"
  },
  {
    id: "miniature-schnauzer",
    name: "Miniature Schnauzer",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Wire",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "schnauzer/miniature",
    petfinderName: "Schnauzer, Miniature"
  },
  {
    id: "shih-tzu",
    name: "Shih Tzu",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Low", activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 18,
    origin: "China", originRegion: "Asia",
    dogCeoPath: "shihtzu",
    petfinderName: "Shih Tzu"
  },
  {
    id: "boston-terrier",
    name: "Boston Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 11, lifespanHigh: 13,
    origin: "USA", originRegion: "North America",
    dogCeoPath: "terrier/boston",
    petfinderName: "Boston Terrier"
  },
  {
    id: "bernese-mountain-dog",
    name: "Bernese Mountain Dog",
    size: "XL", sizeOrder: 5,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 6, lifespanHigh: 8,
    origin: "Switzerland", originRegion: "Europe",
    dogCeoPath: "mountain/bernese",
    petfinderName: "Bernese Mountain Dog"
  },
  {
    id: "pomeranian",
    name: "Pomeranian",
    size: "XS", sizeOrder: 1,
    shed: "Moderate", shedOrder: 2,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 16,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "pomeranian",
    petfinderName: "Pomeranian"
  },
  {
    id: "border-collie",
    name: "Border Collie",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 17,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "collie/border",
    petfinderName: "Border Collie"
  },
  {
    id: "shetland-sheepdog",
    name: "Shetland Sheepdog",
    size: "S", sizeOrder: 2,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "sheepdog/shetland",
    petfinderName: "Shetland Sheepdog (Sheltie)"
  },
  {
    id: "maltese",
    name: "Maltese",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Malta", originRegion: "Europe",
    dogCeoPath: "maltese",
    petfinderName: "Maltese"
  },
  {
    id: "chihuahua",
    name: "Chihuahua",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 14, lifespanHigh: 16,
    origin: "Mexico", originRegion: "North America",
    dogCeoPath: "chihuahua",
    petfinderName: "Chihuahua"
  },
  {
    id: "basset-hound",
    name: "Basset Hound",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "France", originRegion: "Europe",
    dogCeoPath: "hound/basset",
    petfinderName: "Basset Hound"
  },
  {
    id: "mastiff",
    name: "Mastiff",
    size: "XL", sizeOrder: 5,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 6, lifespanHigh: 10,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "mastiff/bull",
    petfinderName: "Mastiff"
  },
  {
    id: "cocker-spaniel",
    name: "Cocker Spaniel",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "High", groomOrder: 3,
    coat: "Medium",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "spaniel/cocker",
    petfinderName: "Cocker Spaniel"
  },
  {
    id: "weimaraner",
    name: "Weimaraner",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 13,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "weimaraner",
    petfinderName: "Weimaraner"
  },
  {
    id: "bichon-frise",
    name: "Bichon Frise",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Curly",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 14, lifespanHigh: 15,
    origin: "Belgium", originRegion: "Europe",
    dogCeoPath: null,
    petfinderName: "Bichon Frise"
  },
  {
    id: "brittany-spaniel",
    name: "Brittany Spaniel",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "France", originRegion: "Europe",
    dogCeoPath: "spaniel/brittany",
    petfinderName: "Brittany Spaniel"
  },
  {
    id: "bull-terrier",
    name: "Bull Terrier",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "terrier/bull",
    petfinderName: "Bull Terrier"
  },
  {
    id: "dalmatian",
    name: "Dalmatian",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 13,
    origin: "Croatia", originRegion: "Europe",
    dogCeoPath: "dalmatian",
    petfinderName: "Dalmatian"
  },
  {
    id: "irish-setter",
    name: "Irish Setter",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Ireland", originRegion: "Europe",
    dogCeoPath: "setter/irish",
    petfinderName: "Setter, Irish"
  },
  {
    id: "samoyed",
    name: "Samoyed",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "Russia", originRegion: "Europe",
    dogCeoPath: "samoyed",
    petfinderName: "Samoyed"
  },
  {
    id: "akita",
    name: "Akita",
    size: "XL", sizeOrder: 5,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 13,
    origin: "Japan", originRegion: "Asia",
    dogCeoPath: "akita",
    petfinderName: "Akita"
  },
  {
    id: "basenji",
    name: "Basenji",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 14,
    origin: "Congo", originRegion: "Africa",
    dogCeoPath: "basenji",
    petfinderName: "Basenji"
  },
  {
    id: "bloodhound",
    name: "Bloodhound",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Belgium", originRegion: "Europe",
    dogCeoPath: "hound/blood",
    petfinderName: "Bloodhound"
  },
  {
    id: "chow-chow",
    name: "Chow Chow",
    size: "M", sizeOrder: 3,
    shed: "High", shedOrder: 3,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Low", activeOrder: 1,
    lifespanLow: 8, lifespanHigh: 12,
    origin: "China", originRegion: "Asia",
    dogCeoPath: "chow",
    petfinderName: "Chow Chow"
  },
  {
    id: "greyhound",
    name: "Greyhound",
    size: "L", sizeOrder: 4,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 13,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "greyhound/italian",
    petfinderName: "Greyhound"
  },
  {
    id: "havanese",
    name: "Havanese",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 14, lifespanHigh: 16,
    origin: "Cuba", originRegion: "North America",
    dogCeoPath: null,
    petfinderName: "Havanese"
  },
  {
    id: "italian-greyhound",
    name: "Italian Greyhound",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 15,
    origin: "Italy", originRegion: "Europe",
    dogCeoPath: "greyhound/italian",
    petfinderName: "Italian Greyhound"
  },
  {
    id: "jack-russell-terrier",
    name: "Jack Russell Terrier",
    size: "S", sizeOrder: 2,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 16,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "terrier/russell",
    petfinderName: "Jack Russell Terrier"
  },
  {
    id: "papillon",
    name: "Papillon",
    size: "XS", sizeOrder: 1,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "France", originRegion: "Europe",
    dogCeoPath: "papillon",
    petfinderName: "Papillon"
  },
  {
    id: "pug",
    name: "Pug",
    size: "S", sizeOrder: 2,
    shed: "High", shedOrder: 3,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "China", originRegion: "Asia",
    dogCeoPath: "pug",
    petfinderName: "Pug"
  },
  {
    id: "vizsla",
    name: "Vizsla",
    size: "L", sizeOrder: 4,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Hungary", originRegion: "Europe",
    dogCeoPath: "vizsla",
    petfinderName: "Vizsla"
  },
  {
    id: "whippet",
    name: "Whippet",
    size: "M", sizeOrder: 3,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "whippet",
    petfinderName: "Whippet"
  },
  {
    id: "wire-fox-terrier",
    name: "Wire Fox Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
    dogCeoPath: "terrier/fox",
    petfinderName: "Fox Terrier (Wire)"
  },
  {
    id: "german-shorthaired-pointer",
    name: "German Shorthaired Pointer",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Germany", originRegion: "Europe",
    dogCeoPath: "pointer/germanlonghair",
    petfinderName: "German Shorthaired Pointer"
  }
];

// Lookup maps built once
export const BREED_BY_ID = Object.fromEntries(BREEDS.map(b => [b.id, b]));
export const BREED_BY_NAME = Object.fromEntries(BREEDS.map(b => [b.name.toLowerCase(), b]));
