// DOGDLE Breed Dataset
// Fields: id, name, size, sizeOrder, shed, shedOrder, groom, groomOrder,
//         coat, active, activeOrder, lifespanLow, lifespanHigh,
//         origin, originRegion

export const BREEDS = [
  {
    id: "labrador-retriever",
    name: "Labrador Retriever",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Canada", originRegion: "North America",
  },
  {
    id: "golden-retriever",
    name: "Golden Retriever",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "german-shepherd",
    name: "German Shepherd",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 9, lifespanHigh: 13,
    origin: "Germany", originRegion: "Europe",
  },
  {
    id: "french-bulldog",
    name: "French Bulldog",
    size: "S", sizeOrder: 2,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "France", originRegion: "Europe",
  },
  {
    id: "bulldog",
    name: "Bulldog",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 8, lifespanHigh: 10,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "poodle",
    name: "Poodle",
    size: "L", sizeOrder: 4,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Curly",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 18,
    origin: "Germany", originRegion: "Europe",
  },
  {
    // Beagle: 20–30 lbs — falls in S range (12–25 lbs border); standard classification is S
    id: "beagle",
    name: "Beagle",
    size: "S", sizeOrder: 2,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "rottweiler",
    name: "Rottweiler",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 8, lifespanHigh: 10,
    origin: "Germany", originRegion: "Europe",
  },
  {
    id: "dachshund",
    name: "Dachshund",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 16,
    origin: "Germany", originRegion: "Europe",
  },
  {
    id: "pembroke-welsh-corgi",
    name: "Pembroke Welsh Corgi",
    size: "S", sizeOrder: 2,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "australian-shepherd",
    name: "Australian Shepherd",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "USA", originRegion: "North America",
  },
  {
    id: "yorkshire-terrier",
    name: "Yorkshire Terrier",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 11, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "boxer",
    name: "Boxer",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Germany", originRegion: "Europe",
  },
  {
    // Siberian Husky: originates from Chukotka, Siberia — geographically Asia
    id: "siberian-husky",
    name: "Siberian Husky",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "Russia", originRegion: "Asia",
  },
  {
    id: "cavalier-king-charles-spaniel",
    name: "Cavalier King Charles Spaniel",
    size: "S", sizeOrder: 2,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 9, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "doberman-pinscher",
    name: "Doberman Pinscher",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Germany", originRegion: "Europe",
  },
  {
    id: "great-dane",
    name: "Great Dane",
    size: "XL", sizeOrder: 5,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 7, lifespanHigh: 10,
    origin: "Germany", originRegion: "Europe",
  },
  {
    id: "miniature-schnauzer",
    name: "Miniature Schnauzer",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Wire",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Germany", originRegion: "Europe",
  },
  {
    id: "shih-tzu",
    name: "Shih Tzu",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Low", activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 18,
    origin: "China", originRegion: "Asia",
  },
  {
    id: "boston-terrier",
    name: "Boston Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 11, lifespanHigh: 13,
    origin: "USA", originRegion: "North America",
  },
  {
    // Bernese Mountain Dog: AKC lifespan 7–10 years (corrected from 6–8)
    id: "bernese-mountain-dog",
    name: "Bernese Mountain Dog",
    size: "XL", sizeOrder: 5,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 7, lifespanHigh: 10,
    origin: "Switzerland", originRegion: "Europe",
  },
  {
    id: "pomeranian",
    name: "Pomeranian",
    size: "XS", sizeOrder: 1,
    shed: "Moderate", shedOrder: 2,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 16,
    origin: "Germany", originRegion: "Europe",
  },
  {
    id: "border-collie",
    name: "Border Collie",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 17,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "shetland-sheepdog",
    name: "Shetland Sheepdog",
    size: "S", sizeOrder: 2,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "maltese",
    name: "Maltese",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Malta", originRegion: "Europe",
  },
  {
    id: "chihuahua",
    name: "Chihuahua",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 14, lifespanHigh: 16,
    origin: "Mexico", originRegion: "North America",
  },
  {
    id: "basset-hound",
    name: "Basset Hound",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "France", originRegion: "Europe",
  },
  {
    id: "mastiff",
    name: "Mastiff",
    size: "XL", sizeOrder: 5,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 6, lifespanHigh: 10,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "cocker-spaniel",
    name: "Cocker Spaniel",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "High", groomOrder: 3,
    coat: "Medium",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "weimaraner",
    name: "Weimaraner",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 13,
    origin: "Germany", originRegion: "Europe",
  },
  {
    id: "bichon-frise",
    name: "Bichon Frise",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Curly",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 14, lifespanHigh: 15,
    origin: "Belgium", originRegion: "Europe",
  },
  {
    id: "brittany-spaniel",
    name: "Brittany Spaniel",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "France", originRegion: "Europe",
  },
  {
    // Bull Terrier: AKC lifespan 12–13 years (corrected from 10–14)
    id: "bull-terrier",
    name: "Bull Terrier",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "dalmatian",
    name: "Dalmatian",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 13,
    origin: "Croatia", originRegion: "Europe",
  },
  {
    id: "irish-setter",
    name: "Irish Setter",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Ireland", originRegion: "Europe",
  },
  {
    // Samoyed: originates from Siberia — geographically Asia
    id: "samoyed",
    name: "Samoyed",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "Russia", originRegion: "Asia",
  },
  {
    // Akita: males 100–130 lbs, females 70–100 lbs — L is more accurate by average weight
    id: "akita",
    name: "Akita",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 13,
    origin: "Japan", originRegion: "Asia",
  },
  {
    id: "basenji",
    name: "Basenji",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 14,
    origin: "Congo", originRegion: "Africa",
  },
  {
    id: "bloodhound",
    name: "Bloodhound",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Belgium", originRegion: "Europe",
  },
  {
    id: "chow-chow",
    name: "Chow Chow",
    size: "M", sizeOrder: 3,
    shed: "High", shedOrder: 3,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Low", activeOrder: 1,
    lifespanLow: 8, lifespanHigh: 12,
    origin: "China", originRegion: "Asia",
  },
  {
    // Greyhound: low-energy at home despite sprinting ability; AKC active level is Low–Moderate
    id: "greyhound",
    name: "Greyhound",
    size: "L", sizeOrder: 4,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 13,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "havanese",
    name: "Havanese",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 14, lifespanHigh: 16,
    origin: "Cuba", originRegion: "North America",
  },
  {
    id: "italian-greyhound",
    name: "Italian Greyhound",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 15,
    origin: "Italy", originRegion: "Europe",
  },
  {
    id: "jack-russell-terrier",
    name: "Jack Russell Terrier",
    size: "S", sizeOrder: 2,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 16,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "papillon",
    name: "Papillon",
    size: "XS", sizeOrder: 1,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "France", originRegion: "Europe",
  },
  {
    id: "pug",
    name: "Pug",
    size: "S", sizeOrder: 2,
    shed: "High", shedOrder: 3,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "China", originRegion: "Asia",
  },
  {
    id: "vizsla",
    name: "Vizsla",
    size: "L", sizeOrder: 4,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Hungary", originRegion: "Europe",
  },
  {
    id: "whippet",
    name: "Whippet",
    size: "M", sizeOrder: 3,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "wire-fox-terrier",
    name: "Wire Fox Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    id: "german-shorthaired-pointer",
    name: "German Shorthaired Pointer",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Germany", originRegion: "Europe",
  },

  // --- NEW BREEDS ---

  {
    // Airedale Terrier: 40–65 lbs (M), wiry double coat, UK origin, 11–14 yrs
    id: "airedale-terrier",
    name: "Airedale Terrier",
    size: "M", sizeOrder: 3,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Afghan Hound: 50–60 lbs (M), long silky coat, Afghanistan, 12–18 yrs
    id: "afghan-hound",
    name: "Afghan Hound",
    size: "L", sizeOrder: 4,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 18,
    origin: "Afghanistan", originRegion: "Middle East",
  },
  {
    // Alaskan Malamute: 75–85 lbs (L), thick double coat, Alaska/USA, 10–14 yrs
    id: "alaskan-malamute",
    name: "Alaskan Malamute",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 14,
    origin: "USA", originRegion: "North America",
  },
  {
    // Australian Cattle Dog: 35–50 lbs (M), short coat, Australia, 12–16 yrs
    id: "australian-cattle-dog",
    name: "Australian Cattle Dog",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 16,
    origin: "Australia", originRegion: "Oceania",
  },
  {
    // Belgian Malinois: 40–80 lbs (M–L); males up to 80 lbs — L by average
    id: "belgian-malinois",
    name: "Belgian Malinois",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 16,
    origin: "Belgium", originRegion: "Europe",
  },
  {
    // Borzoi: 60–105 lbs (L–XL); generally classified as L; silky long coat, Russia, 9–14 yrs
    id: "borzoi",
    name: "Borzoi",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 9, lifespanHigh: 14,
    origin: "Russia", originRegion: "Europe",
  },
  {
    // Cairn Terrier: 13–14 lbs (S), wiry coat, Scotland/UK, 13–15 yrs
    id: "cairn-terrier",
    name: "Cairn Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Cardigan Welsh Corgi: 25–38 lbs (M), medium double coat, Wales/UK, 12–15 yrs
    id: "cardigan-welsh-corgi",
    name: "Cardigan Welsh Corgi",
    size: "M", sizeOrder: 3,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Chesapeake Bay Retriever: 55–80 lbs (L), wavy/short water-resistant coat, USA, 10–13 yrs
    id: "chesapeake-bay-retriever",
    name: "Chesapeake Bay Retriever",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 13,
    origin: "USA", originRegion: "North America",
  },
  {
    // English Setter: 45–80 lbs (L), medium feathered coat, UK, 12 yrs
    id: "english-setter",
    name: "English Setter",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
  },
  {
    // English Springer Spaniel: 40–50 lbs (M), medium coat, UK, 12–14 yrs
    id: "english-springer-spaniel",
    name: "English Springer Spaniel",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Giant Schnauzer: 55–85 lbs (L), wire coat, Germany, 12–15 yrs
    id: "giant-schnauzer",
    name: "Giant Schnauzer",
    size: "L", sizeOrder: 4,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Germany", originRegion: "Europe",
  },
  {
    // Great Pyrenees: 85–115+ lbs (XL), long thick coat, France, 10–12 yrs
    id: "great-pyrenees",
    name: "Great Pyrenees",
    size: "XL", sizeOrder: 5,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "France", originRegion: "Europe",
  },
  {
    // Irish Wolfhound: 105–120+ lbs (XL), wire coat, Ireland, 6–8 yrs
    id: "irish-wolfhound",
    name: "Irish Wolfhound",
    size: "XL", sizeOrder: 5,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 6, lifespanHigh: 8,
    origin: "Ireland", originRegion: "Europe",
  },
  {
    // Keeshond: 35–45 lbs (M), thick double coat (medium), Netherlands, 12–15 yrs
    id: "keeshond",
    name: "Keeshond",
    size: "M", sizeOrder: 3,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Netherlands", originRegion: "Europe",
  },
  {
    // Komondor: 80–100+ lbs (XL), corded coat (Long), Hungary, 10–12 yrs
    id: "komondor",
    name: "Komondor",
    size: "XL", sizeOrder: 5,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Hungary", originRegion: "Europe",
  },
  {
    // Leonberger: 90–170 lbs (XL), lion-like mane, long coat, Germany, 7 yrs
    id: "leonberger",
    name: "Leonberger",
    size: "XL", sizeOrder: 5,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 7, lifespanHigh: 10,
    origin: "Germany", originRegion: "Europe",
  },
  {
    // Lhasa Apso: 12–18 lbs (S), long flowing coat, Tibet/China, 12–15 yrs
    id: "lhasa-apso",
    name: "Lhasa Apso",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Low", activeOrder: 1,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Tibet", originRegion: "Asia",
  },
  {
    // Miniature Pinscher: 8–10 lbs (XS), short coat, Germany, 12–16 yrs
    id: "miniature-pinscher",
    name: "Miniature Pinscher",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 16,
    origin: "Germany", originRegion: "Europe",
  },
  {
    // Newfoundland: 100–150 lbs (XL), thick double coat (long), Canada, 9–10 yrs
    id: "newfoundland",
    name: "Newfoundland",
    size: "XL", sizeOrder: 5,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 9, lifespanHigh: 10,
    origin: "Canada", originRegion: "North America",
  },
  {
    // Norwegian Elkhound: 48–55 lbs (M), medium double coat, Norway, 12–15 yrs
    id: "norwegian-elkhound",
    name: "Norwegian Elkhound",
    size: "M", sizeOrder: 3,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Norway", originRegion: "Europe",
  },
  {
    // Otterhound: 65–115 lbs (L–XL); males 115 lbs, females 65 lbs — L is standard classification
    id: "otterhound",
    name: "Otterhound",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 13,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Pekingese: up to 14 lbs (S), long double coat, China, 12–14 yrs
    id: "pekingese",
    name: "Pekingese",
    size: "S", sizeOrder: 2,
    shed: "Moderate", shedOrder: 2,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Low", activeOrder: 1,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "China", originRegion: "Asia",
  },
  {
    // Pit Bull (American Pit Bull Terrier): 30–65 lbs (M), short coat, USA, 12–16 yrs
    id: "pit-bull",
    name: "Pit Bull",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 16,
    origin: "USA", originRegion: "North America",
  },
  {
    // Rhodesian Ridgeback: 70–85 lbs (L), short coat, Zimbabwe/South Africa, 10–12 yrs
    id: "rhodesian-ridgeback",
    name: "Rhodesian Ridgeback",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Zimbabwe", originRegion: "Africa",
  },
  {
    // Rough Collie: 50–75 lbs (L), long double coat, UK, 12–14 yrs
    id: "rough-collie",
    name: "Rough Collie",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Saluki: 35–65 lbs (L), long silky feathered coat, Middle East, 10–17 yrs
    id: "saluki",
    name: "Saluki",
    size: "L", sizeOrder: 4,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 17,
    origin: "Iran", originRegion: "Middle East",
  },
  {
    // Shar-Pei: 45–60 lbs (M), short bristly coat, China, 8–12 yrs
    id: "shar-pei",
    name: "Shar-Pei",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Low", activeOrder: 1,
    lifespanLow: 8, lifespanHigh: 12,
    origin: "China", originRegion: "Asia",
  },
  {
    // Shiba Inu: 17–23 lbs (S), short double coat, Japan, 13–16 yrs
    id: "shiba-inu",
    name: "Shiba Inu",
    size: "S", sizeOrder: 2,
    shed: "High", shedOrder: 3,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 16,
    origin: "Japan", originRegion: "Asia",
  },
  {
    // Scottish Terrier: 18–22 lbs (S), wire coat, Scotland/UK, 12 yrs
    id: "scottish-terrier",
    name: "Scottish Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Wire",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 11, lifespanHigh: 13,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Soft Coated Wheaten Terrier: 30–45 lbs (M), soft wavy coat, Ireland, 12–14 yrs
    id: "soft-coated-wheaten-terrier",
    name: "Soft Coated Wheaten Terrier",
    size: "M", sizeOrder: 3,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Curly",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "Ireland", originRegion: "Europe",
  },
  {
    // St. Bernard: 120–180 lbs (XL), long or short coat, Switzerland, 8–10 yrs
    id: "st-bernard",
    name: "St. Bernard",
    size: "XL", sizeOrder: 5,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "Low", activeOrder: 1,
    lifespanLow: 8, lifespanHigh: 10,
    origin: "Switzerland", originRegion: "Europe",
  },
  {
    // Staffordshire Bull Terrier: 24–38 lbs (M), short coat, UK, 12–14 yrs
    id: "staffordshire-bull-terrier",
    name: "Staffordshire Bull Terrier",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: "UK", originRegion: "Europe",
  },
  {
    // West Highland White Terrier: 15–22 lbs (S), wire double coat, Scotland/UK, 13–15 yrs
    id: "west-highland-white-terrier",
    name: "West Highland White Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Wire",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Xoloitzcuintli: 10–50 lbs — toy/miniature/standard; standard 30–55 lbs (M); hairless
    id: "xoloitzcuintli",
    name: "Xoloitzcuintli",
    size: "M", sizeOrder: 3,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 13, lifespanHigh: 18,
    origin: "Mexico", originRegion: "North America",
  },

  // --- TERRIERS ---

  {
    // Bedlington Terrier: 17–23 lbs (S), curly lamb-like coat, UK, 11–16 yrs
    id: "bedlington-terrier",
    name: "Bedlington Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Curly",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 11, lifespanHigh: 16,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Border Terrier: 11–16 lbs (S), wiry dense coat, UK, 12–15 yrs
    id: "border-terrier",
    name: "Border Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Irish Terrier: 25–27 lbs (S/M border — classified M by weight), wiry coat, Ireland, 13–15 yrs
    id: "irish-terrier",
    name: "Irish Terrier",
    size: "M", sizeOrder: 3,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "Ireland", originRegion: "Europe",
  },
  {
    // Kerry Blue Terrier: 33–40 lbs (M), soft wavy blue coat, Ireland, 13–15 yrs
    id: "kerry-blue-terrier",
    name: "Kerry Blue Terrier",
    size: "M", sizeOrder: 3,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Curly",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "Ireland", originRegion: "Europe",
  },
  {
    // Lakeland Terrier: 17 lbs (S), wire coat, UK, 12–15 yrs
    id: "lakeland-terrier",
    name: "Lakeland Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Norfolk Terrier: 11–12 lbs (XS/S border — classified S), wire coat, UK, 12–15 yrs
    id: "norfolk-terrier",
    name: "Norfolk Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Norwich Terrier: 12 lbs (S), wire coat, UK, 12–15 yrs
    id: "norwich-terrier",
    name: "Norwich Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Silky Terrier: 8–10 lbs (XS), long silky coat, Australia, 13–15 yrs
    id: "silky-terrier",
    name: "Silky Terrier",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "Australia", originRegion: "Oceania",
  },
  {
    // Welsh Terrier: 20–22 lbs (S), wire coat, Wales/UK, 12–15 yrs
    id: "welsh-terrier",
    name: "Welsh Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Dandie Dinmont Terrier: 18–24 lbs (S), crisp topknot/soft body coat, UK, 12–15 yrs
    id: "dandie-dinmont-terrier",
    name: "Dandie Dinmont Terrier",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },

  // --- SPANIELS ---

  {
    // Clumber Spaniel: 55–85 lbs (L), dense medium coat, UK, 10–12 yrs
    id: "clumber-spaniel",
    name: "Clumber Spaniel",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Irish Water Spaniel: 45–65 lbs (M), tight curly water-resistant coat, Ireland, 12–13 yrs
    id: "irish-water-spaniel",
    name: "Irish Water Spaniel",
    size: "M", sizeOrder: 3,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Curly",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: "Ireland", originRegion: "Europe",
  },
  {
    // Welsh Springer Spaniel: 35–55 lbs (M), medium silky coat, Wales/UK, 12–15 yrs
    id: "welsh-springer-spaniel",
    name: "Welsh Springer Spaniel",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Sussex Spaniel: 35–45 lbs (M), medium wavy coat, UK, 13–15 yrs
    id: "sussex-spaniel",
    name: "Sussex Spaniel",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "Low", activeOrder: 1,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "UK", originRegion: "Europe",
  },

  // --- RETRIEVERS & SETTERS ---

  {
    // Curly-Coated Retriever: 60–95 lbs (L), tight curly coat, UK, 10–12 yrs
    id: "curly-coated-retriever",
    name: "Curly-Coated Retriever",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Curly",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Flat-Coated Retriever: 55–70 lbs (L), dense flat medium coat, UK, 8–10 yrs
    id: "flat-coated-retriever",
    name: "Flat-Coated Retriever",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 8, lifespanHigh: 10,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Gordon Setter: 45–80 lbs (L), medium silky coat, Scotland/UK, 12–13 yrs
    id: "gordon-setter",
    name: "Gordon Setter",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: "UK", originRegion: "Europe",
  },

  // --- HOUNDS ---

  {
    // Ibizan Hound: 45–50 lbs (M), short smooth or wire coat, Spain (Ibiza), 11–14 yrs
    id: "ibizan-hound",
    name: "Ibizan Hound",
    size: "M", sizeOrder: 3,
    shed: "Low", shedOrder: 1,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 14,
    origin: "Spain", originRegion: "Europe",
  },
  {
    // Scottish Deerhound: 75–110 lbs (L–XL); standard classified L, wire/shaggy coat, UK, 8–11 yrs
    id: "scottish-deerhound",
    name: "Scottish Deerhound",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 8, lifespanHigh: 11,
    origin: "UK", originRegion: "Europe",
  },

  // --- HERDING & WORKING ---

  {
    // Old English Sheepdog: 60–100 lbs (L), long thick shaggy coat, UK, 10–12 yrs
    id: "old-english-sheepdog",
    name: "Old English Sheepdog",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "UK", originRegion: "Europe",
  },
  {
    // Belgian Tervuren: 45–75 lbs (L), long double coat, Belgium, 14–16 yrs
    id: "belgian-tervuren",
    name: "Belgian Tervuren",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 16,
    origin: "Belgium", originRegion: "Europe",
  },
  {
    // Belgian Groenendael (Belgian Sheepdog): 45–75 lbs (L), long black double coat, Belgium, 14–16 yrs
    id: "belgian-groenendael",
    name: "Belgian Groenendael",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 16,
    origin: "Belgium", originRegion: "Europe",
  },
  {
    // Bouvier des Flandres: 70–110 lbs (XL), rough double coat, Belgium, 10–12 yrs
    id: "bouvier-des-flandres",
    name: "Bouvier des Flandres",
    size: "XL", sizeOrder: 5,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Wire",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Belgium", originRegion: "Europe",
  },
  {
    // Briard: 55–100 lbs (L), long wavy double coat, France, 12 yrs
    id: "briard",
    name: "Briard",
    size: "L", sizeOrder: 4,
    shed: "Moderate", shedOrder: 2,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "France", originRegion: "Europe",
  },
  {
    // Appenzeller Mountain Dog: 48–70 lbs (M), short tricolor coat, Switzerland, 12–15 yrs
    id: "appenzeller-mountain-dog",
    name: "Appenzeller Mountain Dog",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Switzerland", originRegion: "Europe",
  },
  {
    // Entlebucher Mountain Dog: 40–65 lbs (M), short tricolor coat, Switzerland, 11–13 yrs
    id: "entlebucher-mountain-dog",
    name: "Entlebucher Mountain Dog",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 13,
    origin: "Switzerland", originRegion: "Europe",
  },
  {
    // Greater Swiss Mountain Dog: 85–140 lbs (XL), short dense tricolor coat, Switzerland, 8–11 yrs
    id: "greater-swiss-mountain-dog",
    name: "Greater Swiss Mountain Dog",
    size: "XL", sizeOrder: 5,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 8, lifespanHigh: 11,
    origin: "Switzerland", originRegion: "Europe",
  },
  {
    // Kuvasz: 70–115 lbs (L–XL); classified L, white long double coat, Hungary, 10–12 yrs
    id: "kuvasz",
    name: "Kuvasz",
    size: "L", sizeOrder: 4,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: "Hungary", originRegion: "Europe",
  },

  // --- OTHER ---

  {
    // American Eskimo Dog: 6–35 lbs — standard size 25–35 lbs (M); long white double coat, USA, 13–15 yrs
    id: "american-eskimo-dog",
    name: "American Eskimo Dog",
    size: "M", sizeOrder: 3,
    shed: "High", shedOrder: 3,
    groom: "Moderate", groomOrder: 2,
    coat: "Long",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "USA", originRegion: "North America",
  },
  {
    // Norwegian Buhund: 26–40 lbs (M), medium double coat, Norway, 13–15 yrs
    id: "norwegian-buhund",
    name: "Norwegian Buhund",
    size: "M", sizeOrder: 3,
    shed: "Moderate", shedOrder: 2,
    groom: "Moderate", groomOrder: 2,
    coat: "Medium",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "Norway", originRegion: "Europe",
  },
  {
    // Schipperke: 10–16 lbs (S), dense double coat (short/medium), Belgium, 13–15 yrs
    id: "schipperke",
    name: "Schipperke",
    size: "S", sizeOrder: 2,
    shed: "Moderate", shedOrder: 2,
    groom: "Low", groomOrder: 1,
    coat: "Short",
    active: "High", activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: "Belgium", originRegion: "Europe",
  },
  {
    // Coton de Tulear: 8–15 lbs (S), long cottony white coat, Madagascar, 15–19 yrs
    id: "coton-de-tulear",
    name: "Coton de Tulear",
    size: "S", sizeOrder: 2,
    shed: "Low", shedOrder: 1,
    groom: "High", groomOrder: 3,
    coat: "Long",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 15, lifespanHigh: 19,
    origin: "Madagascar", originRegion: "Africa",
  },
  {
    // Brussels Griffon: 8–10 lbs (XS), rough or smooth coat, Belgium, 12–15 yrs
    id: "brussels-griffon",
    name: "Brussels Griffon",
    size: "XS", sizeOrder: 1,
    shed: "Low", shedOrder: 1,
    groom: "Moderate", groomOrder: 2,
    coat: "Wire",
    active: "Moderate", activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: "Belgium", originRegion: "Europe",
  },
  {
    id: 'affenpinscher',
    name: 'Affenpinscher',
    size: 'XS', sizeOrder: 1,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'american-bulldog',
    name: 'American Bulldog',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'american-english-coonhound',
    name: 'American English Coonhound',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 12,
    origin: 'England', originRegion: 'Europe',
  },
  {
    id: 'american-foxhound',
    name: 'American Foxhound',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 13,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'american-leopard-hound',
    name: 'American Leopard Hound',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'american-staffordshire-terrier',
    name: 'American Staffordshire Terrier',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 16,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'american-water-spaniel',
    name: 'American Water Spaniel',
    size: 'M', sizeOrder: 3,
    shed: 'Low', shedOrder: 1,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 14,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'anatolian-shepherd-dog',
    name: 'Anatolian Shepherd Dog',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 11, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'appenzeller-sennenhund',
    name: 'Appenzeller Sennenhund',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'australian-stumpy-tail-cattle-dog',
    name: 'Australian Stumpy Tail Cattle Dog',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Australia', originRegion: 'Oceania',
  },
  {
    id: 'australian-terrier',
    name: 'Australian Terrier',
    size: 'S', sizeOrder: 2,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 15,
    origin: 'Australia', originRegion: 'Oceania',
  },
  {
    id: 'azawakh',
    name: 'Azawakh',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'West Africa', originRegion: 'Africa',
  },
  {
    id: 'barbet',
    name: 'Barbet',
    size: 'L', sizeOrder: 4,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'France', originRegion: 'Europe',
  },
  {
    id: 'basset-fauve-de-bretagne',
    name: 'Basset Fauve de Bretagne',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 12,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'bavarian-mountain-scent-hound',
    name: 'Bavarian Mountain Scent Hound',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'bearded-collie',
    name: 'Bearded Collie',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'beauceron',
    name: 'Beauceron',
    size: 'XL', sizeOrder: 5,
    shed: 'High', shedOrder: 3,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'belgian-laekenois',
    name: 'Belgian Laekenois',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Belgium', originRegion: 'Europe',
  },
  {
    id: 'belgian-sheepdog',
    name: 'Belgian Sheepdog',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Belgium', originRegion: 'Europe',
  },
  {
    id: 'bergamasco-sheepdog',
    name: 'Bergamasco Sheepdog',
    size: 'L', sizeOrder: 4,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 13, lifespanHigh: 15,
    origin: 'Italy', originRegion: 'Europe',
  },
  {
    id: 'berger-picard',
    name: 'Berger Picard',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: 'France', originRegion: 'Europe',
  },
  {
    id: 'black-and-tan-coonhound',
    name: 'Black and Tan Coonhound',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'black-russian-terrier',
    name: 'Black Russian Terrier',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Russia', originRegion: 'Europe',
  },
  {
    id: 'bluetick-coonhound',
    name: 'Bluetick Coonhound',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 12,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'boerboel',
    name: 'Boerboel',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 9, lifespanHigh: 11,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'bohemian-shepherd',
    name: 'Bohemian Shepherd',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'bolognese',
    name: 'Bolognese',
    size: 'XS', sizeOrder: 1,
    shed: 'Low', shedOrder: 1,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'boykin-spaniel',
    name: 'Boykin Spaniel',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'bracco-italiano',
    name: 'Bracco Italiano',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 14,
    origin: 'Italy', originRegion: 'Europe',
  },
  {
    id: 'braque-francais-pyrenean',
    name: 'Braque Francais Pyrenean',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'brittany',
    name: 'Brittany',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'broholmer',
    name: 'Broholmer',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 8, lifespanHigh: 10,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'bullmastiff',
    name: 'Bullmastiff',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 7, lifespanHigh: 9,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'canaan-dog',
    name: 'Canaan Dog',
    size: 'M', sizeOrder: 3,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Israel', originRegion: 'Middle East',
  },
  {
    id: 'carolina-dog',
    name: 'Carolina Dog',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'caucasian-shepherd-dog',
    name: 'Caucasian Shepherd Dog',
    size: 'XL', sizeOrder: 5,
    shed: 'High', shedOrder: 3,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'central-asian-shepherd-dog',
    name: 'Central Asian Shepherd Dog',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'cesky-terrier',
    name: 'Cesky Terrier',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'chinese-crested',
    name: 'Chinese Crested',
    size: 'S', sizeOrder: 2,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 13, lifespanHigh: 18,
    origin: 'China', originRegion: 'Asia',
  },
  {
    id: 'chinese-shar-pei',
    name: 'Chinese Shar-Pei',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 8, lifespanHigh: 12,
    origin: 'China', originRegion: 'Asia',
  },
  {
    id: 'chinook',
    name: 'Chinook',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'cirneco-dell-etna',
    name: 'Cirneco dell’Etna',
    size: 'M', sizeOrder: 3,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Sicily', originRegion: 'Europe',
  },
  {
    id: 'collie',
    name: 'Collie',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'croatian-sheepdog',
    name: 'Croatian Sheepdog',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'czechoslovakian-vlcak',
    name: 'Czechoslovakian Vlcak',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 15,
    origin: 'Czechoslovakia', originRegion: 'Europe',
  },
  {
    id: 'danish-swedish-farmdog',
    name: 'Danish-Swedish Farmdog',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 13,
    origin: 'Sweden', originRegion: 'Europe',
  },
  {
    id: 'dogo-argentino',
    name: 'Dogo Argentino',
    size: 'XL', sizeOrder: 5,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 9, lifespanHigh: 15,
    origin: 'Argentina', originRegion: 'South America',
  },
  {
    id: 'dogue-de-bordeaux',
    name: 'Dogue de Bordeaux',
    size: 'XL', sizeOrder: 5,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 5, lifespanHigh: 8,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'drentsche-patrijshond',
    name: 'Drentsche Patrijshond',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'drever',
    name: 'Drever',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 15, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'dutch-shepherd',
    name: 'Dutch Shepherd',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 14,
    origin: 'Netherlands', originRegion: 'Europe',
  },
  {
    id: 'english-cocker-spaniel',
    name: 'English Cocker Spaniel',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'England', originRegion: 'Europe',
  },
  {
    id: 'english-foxhound',
    name: 'English Foxhound',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 13,
    origin: 'England', originRegion: 'Europe',
  },
  {
    id: 'english-toy-spaniel',
    name: 'English Toy Spaniel',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'England', originRegion: 'Europe',
  },
  {
    id: 'estrela-mountain-dog',
    name: 'Estrela Mountain Dog',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'eurasier',
    name: 'Eurasier',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 16,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'field-spaniel',
    name: 'Field Spaniel',
    size: 'M', sizeOrder: 3,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'finnish-lapphund',
    name: 'Finnish Lapphund',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Finland', originRegion: 'Europe',
  },
  {
    id: 'finnish-spitz',
    name: 'Finnish Spitz',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: 'Finland', originRegion: 'Europe',
  },
  {
    id: 'german-pinscher',
    name: 'German Pinscher',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Germany', originRegion: 'Europe',
  },
  {
    id: 'german-shepherd-dog',
    name: 'German Shepherd Dog',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 7, lifespanHigh: 10,
    origin: 'Germany', originRegion: 'Europe',
  },
  {
    id: 'german-spitz',
    name: 'German Spitz',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 13, lifespanHigh: 15,
    origin: 'Germany', originRegion: 'Europe',
  },
  {
    id: 'german-wirehaired-pointer',
    name: 'German Wirehaired Pointer',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Wire',
    active: 'High', activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 16,
    origin: 'Germany', originRegion: 'Europe',
  },
  {
    id: 'glen-of-imaal-terrier',
    name: 'Glen of Imaal Terrier',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'grand-basset-griffon-vend-en',
    name: 'Grand Basset Griffon Vendéen',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'hamiltonstovare',
    name: 'Hamiltonstovare',
    size: 'L', sizeOrder: 4,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 17,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'hanoverian-scenthound',
    name: 'Hanoverian Scenthound',
    size: 'XL', sizeOrder: 5,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'harrier',
    name: 'Harrier',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'England', originRegion: 'Europe',
  },
  {
    id: 'hokkaido',
    name: 'Hokkaido',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'hovawart',
    name: 'Hovawart',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'icelandic-sheepdog',
    name: 'Icelandic Sheepdog',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'japanese-chin',
    name: 'Japanese Chin',
    size: 'XS', sizeOrder: 1,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Japan', originRegion: 'Asia',
  },
  {
    id: 'japanese-spitz',
    name: 'Japanese Spitz',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Japan', originRegion: 'Asia',
  },
  {
    id: 'jindo',
    name: 'Jindo',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'kai-ken',
    name: 'Kai Ken',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'karelian-bear-dog',
    name: 'Karelian Bear Dog',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 11, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'kishu-ken',
    name: 'Kishu Ken',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'kromfohrlander',
    name: 'Kromfohrlander',
    size: 'M', sizeOrder: 3,
    shed: 'High', shedOrder: 3,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 13, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'lagotto-romagnolo',
    name: 'Lagotto Romagnolo',
    size: 'M', sizeOrder: 3,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 15, lifespanHigh: 17,
    origin: 'Italy', originRegion: 'Europe',
  },
  {
    id: 'lancashire-heeler',
    name: 'Lancashire Heeler',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'lapponian-herder',
    name: 'Lapponian Herder',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'l-wchen',
    name: 'Löwchen',
    size: 'S', sizeOrder: 2,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 15, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'manchester-terrier-standard',
    name: 'Manchester Terrier (Standard)',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 15, lifespanHigh: 17,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'manchester-terrier-toy',
    name: 'Manchester Terrier (Toy)',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 15, lifespanHigh: 17,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'miniature-american-shepherd',
    name: 'Miniature American Shepherd',
    size: 'M', sizeOrder: 3,
    shed: 'High', shedOrder: 3,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'miniature-bull-terrier',
    name: 'Miniature Bull Terrier',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'mountain-cur',
    name: 'Mountain Cur',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 13,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'mudi',
    name: 'Mudi',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'neapolitan-mastiff',
    name: 'Neapolitan Mastiff',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 7, lifespanHigh: 9,
    origin: 'Italy', originRegion: 'Europe',
  },
  {
    id: 'nederlandse-kooikerhondje',
    name: 'Nederlandse Kooikerhondje',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'norrbottenspets',
    name: 'Norrbottenspets',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 17,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'norwegian-lundehund',
    name: 'Norwegian Lundehund',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Norway', originRegion: 'Europe',
  },
  {
    id: 'nova-scotia-duck-tolling-retriever',
    name: 'Nova Scotia Duck Tolling Retriever',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'parson-russell-terrier',
    name: 'Parson Russell Terrier',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'perro-de-presa-canario',
    name: 'Perro de Presa Canario',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 9, lifespanHigh: 11,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'peruvian-inca-orchid',
    name: 'Peruvian Inca Orchid',
    size: 'M', sizeOrder: 3,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Peru', originRegion: 'South America',
  },
  {
    id: 'petit-basset-griffon-vend-en',
    name: 'Petit Basset Griffon Vendéen',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'pharaoh-hound',
    name: 'Pharaoh Hound',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Egypt', originRegion: 'Africa',
  },
  {
    id: 'plott-hound',
    name: 'Plott Hound',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'pointer',
    name: 'Pointer',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 17,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'polish-lowland-sheepdog',
    name: 'Polish Lowland Sheepdog',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Poland', originRegion: 'Europe',
  },
  {
    id: 'poodle-standard',
    name: 'Poodle (Standard)',
    size: 'L', sizeOrder: 4,
    shed: 'Low', shedOrder: 1,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 18,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'poodle-toy',
    name: 'Poodle (Toy)',
    size: 'XS', sizeOrder: 1,
    shed: 'Low', shedOrder: 1,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 18,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'portuguese-podengo',
    name: 'Portuguese Podengo',
    size: 'L', sizeOrder: 4,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Portugal', originRegion: 'Europe',
  },
  {
    id: 'portuguese-podengo-pequeno',
    name: 'Portuguese Podengo Pequeno',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Portugal', originRegion: 'Europe',
  },
  {
    id: 'portuguese-pointer',
    name: 'Portuguese Pointer',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 14,
    origin: 'Portugal', originRegion: 'Europe',
  },
  {
    id: 'portuguese-sheepdog',
    name: 'Portuguese Sheepdog',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: 'Portugal', originRegion: 'Europe',
  },
  {
    id: 'portuguese-water-dog',
    name: 'Portuguese Water Dog',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 11, lifespanHigh: 13,
    origin: 'Portugal', originRegion: 'Europe',
  },
  {
    id: 'pudelpointer',
    name: 'Pudelpointer',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 14, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'puli',
    name: 'Puli',
    size: 'M', sizeOrder: 3,
    shed: 'Low', shedOrder: 1,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'pumi',
    name: 'Pumi',
    size: 'M', sizeOrder: 3,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'pyrenean-mastiff',
    name: 'Pyrenean Mastiff',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'pyrenean-shepherd',
    name: 'Pyrenean Shepherd',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'rafeiro-do-alentejo',
    name: 'Rafeiro do Alentejo',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'rat-terrier',
    name: 'Rat Terrier',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 18,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'redbone-coonhound',
    name: 'Redbone Coonhound',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'romanian-mioritic-shepherd-dog',
    name: 'Romanian Mioritic Shepherd Dog',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'russell-terrier',
    name: 'Russell Terrier',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'russian-toy',
    name: 'Russian Toy',
    size: 'XS', sizeOrder: 1,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Russia', originRegion: 'Europe',
  },
  {
    id: 'russian-tsvetnaya-bolonka',
    name: 'Russian Tsvetnaya Bolonka',
    size: 'XS', sizeOrder: 1,
    shed: 'Low', shedOrder: 1,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 16,
    origin: 'Russia', originRegion: 'Europe',
  },
  {
    id: 'saint-bernard',
    name: 'Saint Bernard',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 8, lifespanHigh: 10,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'schapendoes',
    name: 'Schapendoes',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'sealyham-terrier',
    name: 'Sealyham Terrier',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'skye-terrier',
    name: 'Skye Terrier',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'sloughi',
    name: 'Sloughi',
    size: 'M', sizeOrder: 3,
    shed: 'Low', shedOrder: 1,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 15,
    origin: 'Morocco', originRegion: 'Africa',
  },
  {
    id: 'slovakian-wirehaired-pointer',
    name: 'Slovakian Wirehaired Pointer',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Wire',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'slovensky-cuvac',
    name: 'Slovensky Cuvac',
    size: 'XL', sizeOrder: 5,
    shed: 'High', shedOrder: 3,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 11, lifespanHigh: 13,
    origin: 'Slovakia', originRegion: 'Europe',
  },
  {
    id: 'slovensky-kopov',
    name: 'Slovensky Kopov',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 13,
    origin: 'Slovakia', originRegion: 'Europe',
  },
  {
    id: 'small-munsterlander-pointer',
    name: 'Small Munsterlander Pointer',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'smooth-fox-terrier',
    name: 'Smooth Fox Terrier',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Short',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'spanish-mastiff',
    name: 'Spanish Mastiff',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Spain', originRegion: 'Europe',
  },
  {
    id: 'spanish-water-dog',
    name: 'Spanish Water Dog',
    size: 'M', sizeOrder: 3,
    shed: 'Low', shedOrder: 1,
    groom: 'High', groomOrder: 3,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Spain', originRegion: 'Europe',
  },
  {
    id: 'stabyhoun',
    name: 'Stabyhoun',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'standard-schnauzer',
    name: 'Standard Schnauzer',
    size: 'M', sizeOrder: 3,
    shed: 'Low', shedOrder: 1,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 13, lifespanHigh: 16,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'swedish-lapphund',
    name: 'Swedish Lapphund',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Sweden', originRegion: 'Europe',
  },
  {
    id: 'swedish-vallhund',
    name: 'Swedish Vallhund',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Sweden', originRegion: 'Europe',
  },
  {
    id: 'taiwan-dog',
    name: 'Taiwan Dog',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 9, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'teddy-roosevelt-terrier',
    name: 'Teddy Roosevelt Terrier',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 14, lifespanHigh: 16,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'thai-ridgeback',
    name: 'Thai Ridgeback',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 13,
    origin: 'Thailand', originRegion: 'Asia',
  },
  {
    id: 'tibetan-mastiff',
    name: 'Tibetan Mastiff',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Tibet', originRegion: 'Asia',
  },
  {
    id: 'tibetan-spaniel',
    name: 'Tibetan Spaniel',
    size: 'S', sizeOrder: 2,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Tibet', originRegion: 'Asia',
  },
  {
    id: 'tibetan-terrier',
    name: 'Tibetan Terrier',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Moderate', groomOrder: 2,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 15, lifespanHigh: 16,
    origin: 'Tibet', originRegion: 'Asia',
  },
  {
    id: 'tosa',
    name: 'Tosa',
    size: 'XL', sizeOrder: 5,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Low', activeOrder: 1,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'toy-fox-terrier',
    name: 'Toy Fox Terrier',
    size: 'XS', sizeOrder: 1,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 13, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'treeing-tennessee-brindle',
    name: 'Treeing Tennessee Brindle',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'treeing-walker-coonhound',
    name: 'Treeing Walker Coonhound',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 12, lifespanHigh: 13,
    origin: 'United States', originRegion: 'North America',
  },
  {
    id: 'wetterhoun',
    name: 'Wetterhoun',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'Moderate', activeOrder: 2,
    lifespanLow: 13, lifespanHigh: 13,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'wirehaired-pointing-griffon',
    name: 'Wirehaired Pointing Griffon',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Wire',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'wirehaired-vizsla',
    name: 'Wirehaired Vizsla',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Wire',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 14,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'working-kelpie',
    name: 'Working Kelpie',
    size: 'L', sizeOrder: 4,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 12, lifespanHigh: 15,
    origin: 'Unknown', originRegion: 'Unknown',
  },
  {
    id: 'yakutian-laika',
    name: 'Yakutian Laika',
    size: 'M', sizeOrder: 3,
    shed: 'Moderate', shedOrder: 2,
    groom: 'Low', groomOrder: 1,
    coat: 'Medium',
    active: 'High', activeOrder: 3,
    lifespanLow: 10, lifespanHigh: 12,
    origin: 'Unknown', originRegion: 'Unknown',
  }

];

// Lookup maps built once
export const BREED_BY_ID = Object.fromEntries(BREEDS.map(b => [b.id, b]));
export const BREED_BY_NAME = Object.fromEntries(BREEDS.map(b => [b.name.toLowerCase(), b]));
